import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import Auth from '../components/Auth'
import Layout from '../components/Layout'
import Notification from '../components/Notification'
import { useAppSelector } from '../store'
import { fetchData, sendCartData } from '../store/cart-actions'
import styles from '../styles/Home.module.css'

let isFirstRender = true

const Home: NextPage = () => {
  const dispatch = useDispatch()
  const notification = useAppSelector(state => state.ui.notification)
  const cart = useAppSelector(state => state.cart)
  const isLoggedIn = useAppSelector(state => state.auth.isLoggedIn)

  useEffect(() => {
    dispatch(fetchData())
  }, [dispatch])

  useEffect(() => {
    if(isFirstRender) {
      isFirstRender = false

      return
    }

    if (cart.changed) {
      dispatch(sendCartData(cart))
    }
  }, [cart, dispatch])
  
  return (
    <>
      {
        notification && 

        <Notification 
          type={notification?.type || 'info'} 
          message={notification.message || ''} 
        />
      }
      
      <div className={styles.container}>
        <Head>
          <title>Shopping Cart</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

          {!isLoggedIn && <Auth />}

          {isLoggedIn && <Layout />}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
          Powered by Victor
          </a>
        </footer>
      </div>
    </>
  )
}

export default Home
